/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D TOTEM.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.598, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom"].geometry}
          material={materials.tq_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_1"].geometry}
          material={materials.tq_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_2"].geometry}
          material={materials.tq_ARD_edge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_3"].geometry}
          material={materials["tq_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_4"].geometry}
          material={materials["tq_ARD_front.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D TOTEM.gltf");